---
title: "微生物溯源"
author: "yjl"
date: "2020/3/24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(knitr)
```

## 一、SourceTracker

### 1、数据准备
#### 原数据及示例文件
https://github.com/danknights/sourcetracker 文件格式及SourceTracker.r
#### 载入数据
样本数据otu_norm_air.txt；源数据otu_norm_human.txt；otu_norm_plant.txt，放在data文件夹
```{r}
source_human_oral <- read.table('data//otu_norm_human_oral.txt',header = T)
head(source_human_oral)

source_plant <- read.table('data//otu_norm_plant.txt',header = T)
head(source_plant)

sink <- read.table('data//otu_norm_air.txt',header = T)
head(sink)

source <- merge(source_human_oral,source_plant,by='ID',all.y=T)
source[is.na(source)]<-0#去掉缺失值，都变为0
data <- merge(sink,source,by='ID',all.y=T)
data[is.na(data)]<-0

source2 <- read.table("data//otus_human_soil.txt",header = T)
data_all <- merge(data,source2,by='ID',all.y=T)
data_all[is.na(data_all)]<-0

names(data_all) [1]<- "#OTU ID"
write.table(data_all,'data//otus.txt',quote = F, sep = "\t",row.names = F,col.names = T,eol = "\n",dec = ".",append = FALSE)
```
转换成示例格式

```{r, engine = 'sh', count_line}

sed -i '1i\# QIIME-formatted OTU table' data//otus.txt
```
载入样品信息表格,放在data文件夹
```{r}
metadata <- read.table('data/metadata.txt',sep='\t',h=T,row.names=1,check=F,comment='')
head(metadata)
```

### 2、溯源
#### 加载sourcetracker.r，放在src文件夹下
```{r}
source('src/SourceTracker.r')
```
#### 全部运行
```{r}
# load OTU table
# This 'read.table' command is designed for a 
# QIIME-formatted OTU table.
# namely, the first line begins with a '#' sign
# and actually _is_ a comment; the second line
# begins with a '#' sign but is actually the header
otus <- read.table('data/otus.txt',sep='\t', header=T,row.names=1,check=F,skip=1,comment='')
otus <- t(as.matrix(otus))

# extract only those samples in common between the two tables
common.sample.ids <- intersect(rownames(metadata), rownames(otus))
otus <- otus[common.sample.ids,]
metadata <- metadata[common.sample.ids,]
# double-check that the mapping file and otu table
# had overlapping samples
if(length(common.sample.ids) <= 1) {
    message <- paste(sprintf('Error: there are %d sample ids in common '),
                    'between the metadata file and data table')
    stop(message)
}

# extract the source environments and source/sink indices
train.ix <- which(metadata$SourceSink=='source')
test.ix <- which(metadata$SourceSink=='sink')
envs <- metadata$Env
if(is.element('Description',colnames(metadata))) desc <- metadata$Description


# tune the alpha values using cross-validation (this is slow!)
# tune.results <- tune.st(otus[train.ix,], envs[train.ix])
# alpha1 <- tune.results$best.alpha1
# alpha2 <- tune.results$best.alpha2
# note: to skip tuning, run this instead:
alpha1 <- alpha2 <- 0.001

# train SourceTracker object on training data
st <- sourcetracker(otus[train.ix,], envs[train.ix])

# Estimate source proportions in test data
results <- predict(st,otus[test.ix,], alpha1=alpha1, alpha2=alpha2)

# Estimate leave-one-out source proportions in training data 
results.train <- predict(st, alpha1=alpha1, alpha2=alpha2)

# plot results
labels <- sprintf('%s %s', envs,desc)
# plot(results, labels[test.ix], type='pie')

#other plotting functions
# plot(results, labels[test.ix], type='bar')
# plot(results, labels[test.ix], type='dist')
# plot(results.train, labels[train.ix], type='pie')
# plot(results.train, labels[train.ix], type='bar')
# plot(results.train, labels[train.ix], type='dist')

# plot results with legend
plot(results, labels[test.ix], type='pie', include.legend=TRUE, env.colors=c('#47697E','#5B7444','#CC6666','#79BEDB','#885588'))
```









